"""Initial migration

Revision ID: 5c9fd931ac46
Revises: d31ed666d06a
Create Date: 2024-08-20 17:46:38.824124

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '5c9fd931ac46'
down_revision: Union[str, None] = 'd31ed666d06a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('employee_onboarding')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('employee_onboarding',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('FirstName', mysql.VARCHAR(length=100), nullable=False),
    sa.Column('LastName', mysql.VARCHAR(length=100), nullable=False),
    sa.Column('DateOfBirth', sa.DATE(), nullable=False),
    sa.Column('ContactNumber', mysql.VARCHAR(length=15), nullable=False),
    sa.Column('EmailAddress', mysql.VARCHAR(length=100), nullable=False),
    sa.Column('Address', mysql.TEXT(), nullable=False),
    sa.Column('Nationality', mysql.VARCHAR(length=50), nullable=False),
    sa.Column('Gender', mysql.VARCHAR(length=10), nullable=True),
    sa.Column('MaritalStatus', mysql.VARCHAR(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    # ### end Alembic commands ###
