"""Initial migration

Revision ID: aa290d59f718
Revises: 5c9fd931ac46
Create Date: 2024-08-20 17:52:49.253590

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'aa290d59f718'
down_revision: Union[str, None] = '5c9fd931ac46'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('employee_onboarding')
    op.drop_index('employment_id', table_name='employee_employment_details')
    op.drop_table('employee_employment_details')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('employee_employment_details',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('employment_id', mysql.VARCHAR(length=20), nullable=False),
    sa.Column('job_position', mysql.VARCHAR(length=100), nullable=False),
    sa.Column('department', mysql.VARCHAR(length=100), nullable=False),
    sa.Column('start_date', sa.DATE(), nullable=False),
    sa.Column('employment_type', mysql.VARCHAR(length=50), nullable=False),
    sa.Column('reporting_manager', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('work_location', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('basic_salary', mysql.DECIMAL(precision=10, scale=2), nullable=True),
    sa.Column('is_active', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True),
    sa.Column('releave_date', sa.DATE(), nullable=True),
    sa.Column('employee_onboarding_id', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['employee_onboarding_id'], ['employee_onboarding.id'], name='employee_employment_details_ibfk_1'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index('employment_id', 'employee_employment_details', ['employment_id'], unique=True)
    op.create_table('employee_onboarding',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('FirstName', mysql.VARCHAR(length=100), nullable=False),
    sa.Column('LastName', mysql.VARCHAR(length=100), nullable=False),
    sa.Column('DateOfBirth', sa.DATE(), nullable=False),
    sa.Column('ContactNumber', mysql.VARCHAR(length=15), nullable=False),
    sa.Column('EmailAddress', mysql.VARCHAR(length=100), nullable=False),
    sa.Column('Address', mysql.TEXT(), nullable=False),
    sa.Column('Nationality', mysql.VARCHAR(length=50), nullable=False),
    sa.Column('Gender', mysql.VARCHAR(length=10), nullable=True),
    sa.Column('MaritalStatus', mysql.VARCHAR(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    # ### end Alembic commands ###
